version: '3'
services:
    steem:
        image: razikus/steembot
        environment:
         - STEEM_USER=NONE
         - POSTING_KEY_PRV=NONE
         - BOT_API_KEY=NONE
         - COOKIE_SECRET=NONE
         - VERBOSE_LOGGING=true
         - MONGODB_URI=mongodb://admin:admin@mongodb:27017/steem
        networks:
         - steemNet
        depends_on:
         - "mongodb"
        restart: on-failure
    mongodb:
        image: tutum/mongodb
        environment:
         - MONGODB_PASS=admin
         - MONGODB_DATABASE=steem
        networks:
         - steemNet


networks:
        steemNet:


            
